### PR TITLE
precompiled

### PR DESCRIPTION
**Pull request by Deathemonic**
a pre compiled version of the program so you don't have to use Cargo to run the program and added a PKGBUILD so it could be installed in the AUR

### CODE REVIEW

**Comment by mrshmllow** [comment]
what steps should i take to have it on the AUR? I originally wrote one

**Comment by Deathemonic** [comment]
you just have to follow this from the wiki https://wiki.archlinux.org/title/AUR_submission_guidelines, https://wiki.archlinux.org/title/Arch_User_Repository#Submitting_packages

here's a video from distrotube:
https://www.youtube.com/watch?v=iUz28vbWgVw

**Comment by mrshmllow** [comment]
Running makepkg and installing it produces a broken (`zsh: permission denied: gh-cal`) binaries

**Comment by Deathemonic** [comment]
hmm maybe it could be it not setting as a excutable try chmod +x ./gh-cal if it runs

**Comment by Deathemonic** [comment]
I think I have to edit the PKGBUILD

**Comment by mrshmllow** [comment]
Should now work

**Pull request merged**
